server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.4.14.191:3306/my_db
    username: root
    password: zhangruixin
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 49.4.14.191
    port: 6379
    timeout: 5000
    password: zhangruixin
  # Elasticsearch 配置
  # todo 需替换配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456